import nbformat

nb = nbformat.v4.new_notebook()
nb.cells = [
    nbformat.v4.new_markdown_cell("# Atelier 1 — Notebook 3 : Allocation des coûts non taggés"),
    nbformat.v4.new_code_cell(
        "import pandas as pd\n"
        "import plotly.express as px\n"
        "from pathlib import Path\n"
        "\n"
        "df = pd.read_csv(Path('../../ressources/datasets/cur_sample.csv'), parse_dates=['usage_date'])\n"
        "for col in ['tag_team', 'tag_env', 'tag_project']:\n"
        "    df[col] = df[col].replace('', pd.NA)\n"
        "\n"
        "df_tagged   = df[df['tag_team'].notna()].copy()\n"
        "df_untagged = df[df['tag_team'].isna()].copy()\n"
        "\n"
        "print(f'Couts tagges    : ${df_tagged.unblended_cost.sum():,.2f}')\n"
        "print(f'Couts non tagges: ${df_untagged.unblended_cost.sum():,.2f}')\n"
        "print(f'Total           : ${df.unblended_cost.sum():,.2f}')"
    ),
    nbformat.v4.new_markdown_cell(
        "## Méthode 1 : Even split\n\n"
        "Le coût non taggé est divisé également entre toutes les équipes identifiées."
    ),
    nbformat.v4.new_code_cell(
        "def allocate_even(df_tagged: pd.DataFrame, df_untagged: pd.DataFrame) -> pd.DataFrame:\n"
        "    \"\"\"\n"
        "    Répartit les coûts non taggés à parts égales entre toutes les équipes.\n"
        "    Retourne un DataFrame [tag_team, cout_tagge, cout_alloue, cout_total].\n"
        "    \"\"\"\n"
        "    cout_tagge = (\n"
        "        df_tagged.groupby('tag_team')['unblended_cost']\n"
        "                 .sum()\n"
        "                 .reset_index()\n"
        "                 .rename(columns={'unblended_cost': 'cout_tagge'})\n"
        "    )\n"
        "    nb_equipes = len(cout_tagge)\n"
        "    total_untagged = df_untagged['unblended_cost'].sum()\n"
        "    part_egale = total_untagged / nb_equipes\n"
        "    cout_tagge['cout_alloue'] = part_egale\n"
        "    cout_tagge['cout_total'] = cout_tagge['cout_tagge'] + cout_tagge['cout_alloue']\n"
        "    return cout_tagge.sort_values('cout_total', ascending=False).reset_index(drop=True)\n"
        "\n"
        "result_even = allocate_even(df_tagged, df_untagged)\n"
        "display(result_even)"
    ),
    nbformat.v4.new_markdown_cell(
        "## Méthode 2 : Proportional\n\n"
        "Le coût non taggé est réparti proportionnellement au coût taggé de chaque équipe."
    ),
    nbformat.v4.new_code_cell(
        "def allocate_proportional(df_tagged: pd.DataFrame, df_untagged: pd.DataFrame) -> pd.DataFrame:\n"
        "    \"\"\"\n"
        "    Répartit les coûts non taggés proportionnellement aux coûts taggés par équipe.\n"
        "    Retourne un DataFrame avec le coût total alloué par équipe.\n"
        "    \"\"\"\n"
        "    cout_tagge = (\n"
        "        df_tagged.groupby('tag_team')['unblended_cost']\n"
        "                 .sum()\n"
        "                 .reset_index()\n"
        "                 .rename(columns={'unblended_cost': 'cout_tagge'})\n"
        "    )\n"
        "    cout_tagge['part'] = cout_tagge['cout_tagge'] / cout_tagge['cout_tagge'].sum()\n"
        "    total_untagged = df_untagged['unblended_cost'].sum()\n"
        "    cout_tagge['cout_alloue'] = cout_tagge['part'] * total_untagged\n"
        "    cout_tagge['cout_total'] = cout_tagge['cout_tagge'] + cout_tagge['cout_alloue']\n"
        "    return (\n"
        "        cout_tagge[['tag_team', 'cout_tagge', 'cout_alloue', 'cout_total']]\n"
        "        .sort_values('cout_total', ascending=False)\n"
        "        .reset_index(drop=True)\n"
        "    )\n"
        "\n"
        "result_proportional = allocate_proportional(df_tagged, df_untagged)\n"
        "display(result_proportional)"
    ),
    nbformat.v4.new_markdown_cell(
        "## Méthode 3 : Custom weights\n\n"
        "Pondération métier : platform reçoit 50% de sa part proportionnelle."
    ),
    nbformat.v4.new_code_cell(
        "WEIGHTS = {\n"
        "    'platform': 0.5,\n"
        "    'payments': 1.0,\n"
        "    'data':     1.0,\n"
        "    'frontend': 1.0,\n"
        "}\n"
        "\n"
        "def allocate_weighted(df_tagged: pd.DataFrame, df_untagged: pd.DataFrame,\n"
        "                      weights: dict) -> pd.DataFrame:\n"
        "    cout_tagge = (\n"
        "        df_tagged.groupby('tag_team')['unblended_cost']\n"
        "                 .sum()\n"
        "                 .reset_index()\n"
        "                 .rename(columns={'unblended_cost': 'cout_tagge'})\n"
        "    )\n"
        "    cout_tagge['poids'] = cout_tagge['tag_team'].map(weights).fillna(1.0)\n"
        "    cout_tagge['cout_pondere'] = cout_tagge['cout_tagge'] * cout_tagge['poids']\n"
        "    base_ponderee = cout_tagge['cout_pondere'].sum()\n"
        "    cout_tagge['part'] = cout_tagge['cout_pondere'] / base_ponderee\n"
        "    total_untagged = df_untagged['unblended_cost'].sum()\n"
        "    cout_tagge['cout_alloue'] = cout_tagge['part'] * total_untagged\n"
        "    cout_tagge['cout_total'] = cout_tagge['cout_tagge'] + cout_tagge['cout_alloue']\n"
        "    return (\n"
        "        cout_tagge[['tag_team', 'cout_tagge', 'poids', 'cout_alloue', 'cout_total']]\n"
        "        .sort_values('cout_total', ascending=False)\n"
        "        .reset_index(drop=True)\n"
        "    )\n"
        "\n"
        "result_weighted = allocate_weighted(df_tagged, df_untagged, WEIGHTS)\n"
        "display(result_weighted)"
    ),
    nbformat.v4.new_markdown_cell("## Graphique de comparaison des 3 méthodes"),
    nbformat.v4.new_code_cell(
        "comparison = pd.DataFrame({\n"
        "    'equipe': result_proportional['tag_team'],\n"
        "    'Even split':   result_even.set_index('tag_team').loc[result_proportional['tag_team'], 'cout_total'].values,\n"
        "    'Proportional': result_proportional['cout_total'].values,\n"
        "    'Custom weights': result_weighted.set_index('tag_team').loc[result_proportional['tag_team'], 'cout_total'].values,\n"
        "})\n"
        "\n"
        "comparison_melted = comparison.melt(id_vars='equipe', var_name='methode', value_name='cout_total')\n"
        "\n"
        "fig = px.bar(\n"
        "    comparison_melted,\n"
        "    x='equipe', y='cout_total', color='methode',\n"
        "    barmode='group',\n"
        "    title='Comparaison des 3 méthodes d\\'allocation par équipe',\n"
        "    labels={'cout_total': 'Coût total alloué ($)', 'equipe': 'Équipe', 'methode': 'Méthode'},\n"
        "    color_discrete_sequence=['#1f77b4', '#2ca02c', '#d62728']\n"
        ")\n"
        "fig.update_layout(yaxis_tickprefix='$', yaxis_tickformat=',.0f')\n"
        "fig.show()\n"
        "print('=> Sauvegarder ce graphique avec le bouton camera en haut a droite du graphique')"
    ),
]

nbformat.write(nb, '03-allocation-exercice.ipynb')
print("OK - notebook 03 prof cree")
